services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    env_file: ".env"
    ports:
      - "3000:8080"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
